version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresql
    ports:
      - 5432

  redis:
    container_name: api_redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  nodejs:
    container_name: api_node
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: docker/node
      target: dependencies
    ports:
      - ${VITE_APP_PORT}:${VITE_APP_PORT}
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./:/var/www/api

volumes:
  postgres_volume:
  redis_volume:
