version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    ports:
      - ${VITE_MONGO_INITDB_PORT}:${VITE_MONGO_INITDB_PORT}
    networks:
      - services
    volumes:
      - mongo_volume:/data/db
      - mongo_log:/var/log/mongodb
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    env_file:
      - .env
    environment:
      VITE_MONGO_INITDB_USERNAME: ${VITE_MONGO_INITDB_USERNAME}
      VITE_MONGO_INITDB_PASSWORD: ${VITE_MONGO_INITDB_PASSWORD}
      VITE_MONGO_INITDB_DATABASE: ${VITE_MONGO_INITDB_DATABASE}
      VITE_MONGO_INITDB_HOST: ${VITE_MONGO_INITDB_HOST}

  redis:
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  nodejs:
    container_name: api_node
    restart: always
    depends_on:
      - mongodb
      - redis
    build:
      context: docker/node
      target: dependencies
    ports:
      - ${VITE_APP_PORT}:${VITE_APP_PORT}
    env_file:
      - .env
    volumes:
      - ./:/var/www/api
    command: dumb-init node build/app.js

volumes:
  mongo_volume:
  mongo_log:
  redis_volume:

networks:
  services:
    name: ${VITE_MONGO_INITDB_HOST:-mongodb.network}
